version: '3.8'

services:
  app:
    image: golang:1.22
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    command: go run -tags=pprof main.go
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - ENABLE_PPROF=true
      - GO111MODULE=on
      - NATS_URL=nats://nats:4222
    ports:
      - "8080:8080"
      - "6060:6060"  # pprof endpoint
    depends_on:
      - nats
      - nats-streaming
      - kafka

  nats:
    image: nats:2.10.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --config /etc/nats/nats.conf
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf
      - nats-data:/data/nats

  nats-streaming:
    image: nats-streaming:0.25.6
    ports:
      - "4223:4222"
    command: -cid event-processor-cluster -store file -dir /data/nats-streaming
    volumes:
      - nats-streaming-data:/data/nats-streaming
    depends_on:
      - nats

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./config/kafka.conf:/etc/kafka/kafka.conf
    depends_on:
      - zookeeper

volumes:
  go-mod-cache:
  nats-data:
  nats-streaming-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data: 