name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4

      - name: Lint
        run: golangci-lint run -c .golangci.yml ./...

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Run nats as prerequisite
        run: |
          docker compose up -d nats
          sleep 10

      - name: Run Tests
        env:
          NATS_URL: ${{ secrets.NATS_URL }}
        run: |
          # Run tests with coverage and race detection
          echo "NATS_URL: ${{ env.NATS_URL }}"
          NATS_URL=${{ env.NATS_URL }} go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Build
        run: go build -v ./...

  e2e-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Run E2E Tests with Profiling
        run: |
          # TODO: Run load requests on API and collect CPU profile
          
          # Collect memory profile
          curl -o mem.prof http://localhost:6060/debug/pprof/heap

          # Collect goroutine profile
          curl -o goroutine.prof http://localhost:6060/debug/pprof/goroutine

      - name: Analyze Profiles
        run: |
          # Analyze CPU profile
          go tool pprof -text cpu.prof > cpu_analysis.txt
          
          # Analyze memory profile
          go tool pprof -text mem.prof > mem_analysis.txt
          
          # Analyze goroutine profile
          go tool pprof -text goroutine.prof > goroutine_analysis.txt

      - name: Upload Profile Analysis
        uses: actions/upload-artifact@v4
        with:
          name: profile-analysis
          path: |
            cpu_analysis.txt
            mem_analysis.txt
            goroutine_analysis.txt

      - name: Cleanup
        if: always()
        run: docker compose down -v --remove-orphans
